name: Publish 'kwarclegal' Docker Image

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: fau-cdi/odbcd:withkwarclegal
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7
  GO_VERSION: '~1.19.2'
  GO_STABLE: 'true'
  NODE_VERSION: '16'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: ${{ env.GO_STABLE }}
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Run 'make deps'
        run: make deps
      - name: Run 'make generate'
        env:
          LEGAL_JS_TEXT: "For legal reasons we must link"
          LEGAL_JS_SOURCE: "https://privacy.kwarc.info/legal.js"
        run: make generate
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          platforms: ${{ env.PLATFORMS }}
          pull: true
          push: true